apiVersion: v1
kind: Pod
metadata:
  name: mysqldb-pod
  labels:
    name: mysqldb-pod
    app: user-login-app
spec:
  containers:
    - name: mysqldb
      image: adarsha/kub_demo_mysqldb:1.0
      ports:
        - containerPort: 3306